name: securities_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    # StateManagement
  rxdart: ^0.27.7
    # JsonParser
  json_annotation: ^4.9.0

    # Http Client
  dio: ^5.4.3+1

    #Svg Loader
  flutter_svg: ^2.0.10+1

    # Local Persist
  shared_preferences: ^2.2.3

    # Simple direct Service Locator
  injectable: ^2.4.2
  get_it: ^7.7.0

    # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.1.0



  collection: ^1.18.0

  pretty_dio_logger: ^1.3.1

  #socket client
  socket_io_client: ^1.0.2
  sails_io: ^0.0.2
  connectivity_plus: ^6.0.3
  
  uuid: ^4.4.0
  flutter_gen: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  json_serializable:
  freezed:
  freezed_annotation:
  flutter_lints:
  injectable_generator: ^2.6.1


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
#    flare_flutter: true
#    rive: true
#    lottie: true



flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true